services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  front:
    build: ./public
    ports:
      - 3000:3000
  api:
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - mongo